fix: update to add atmos, homelab, more

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -4,7 +4,7 @@ version: "3"
 silent: true
 vars:
   TARGET:
-    sh: 'echo "${TARGET:-"local"}"'
+    sh: 'echo "${TARGET:-"dev"}"'
   PROFILE:
     sh: 'echo "${PROFILE:-"default"}"'
   PROJECT:
@@ -194,57 +194,54 @@ tasks:
     status:
       - "test -f /usr/local/share/zsh/site-functions/_task"
 
-  deploy:
-    cmds:
-      - |
-        mkdir -p {{.ROOT_DIR}}/secrets/{{.TARGET}}
-        echo "TARGET: {{.TARGET}}"
-        echo "TERRAFORM: {{.TERRAFORM}}"
-        {{.TERRAFORM}} -chdir=infrastructure/environments/{{.TARGET}} init -upgrade -migrate-state
-        {{.TERRAFORM}} -chdir=infrastructure/environments/{{.TARGET}} plan -out=terraform.tfplan
-        {{.TERRAFORM}} -chdir=infrastructure/environments/{{.TARGET}} apply -parallelism=1 terraform.tfplan
-
-  deploy:all:
-    cmds:
-      - task: deploy
-        vars:
-          TARGET: local
-      - task: deploy
-        vars:
-          TARGET: local/cluster1
-      - task: deploy
-        vars:
-          TARGET: local/cluster2
-
-  destroy:
-    cmds:
-      - |
-        echo "TARGET: {{.TARGET}}"
-        echo "TERRAFORM: {{.TERRAFORM}}"
-        {{.TERRAFORM}} -chdir=infrastructure/environments/{{.TARGET}} destroy -parallelism=1 -auto-approve
-
-  destroy:all:
-    cmds:
-      - task: destroy
-        vars:
-          TARGET: local/cluster1
-      - task: destroy
-        vars:
-          TARGET: local/cluster2
-      - task: destroy
-        vars:
-          TARGET: local
-      - |
-        rm -rf ./secrets/local
-
   clean:
     cmds:
       - |
-        #k3d cluster delete cluster1 || true
         kind delete cluster -n cluster1 || true
         kind delete cluster -n cluster2 || true
-        rm -rf ./infrastructure/environments/{{.TARGET}}/.terraform
-        rm -rf ./infrastructure/environments/{{.TARGET}}/cluster1/.terraform
-        rm -rf ./infrastructure/environments/{{.TARGET}}/cluster2/.terraform
-        find ./infrastructure/environments/{{.TARGET}} -type f \( -name "*.tfstate" -o -name "*.tfplan" -o -name "*.terraform" -o -name "*.lock.hcl" \) -exec rm -f {} + || true
+        rm -rf ./components/terraform/*/.terraform
+        find ./components/terraform/ -type f \( -name "*.tfstate" -o -name "*.tfplan" -o -name "*.terraform" -o -name "*.lock.hcl" \) -exec rm -f {} + || true
+        find ./components/terraform/ -type d \( -name "*.tfstate.d" \) -exec rm -rf {} + || true
         find ./secrets/{{.TARGET}} -type f \( -name "*.tfstate" -o -name "*.tfplan" -o -name ".terraform" -o -name "tfplan.json" \) -exec rm -f {} + || true
+
+  atmos:
+    desc: Run atmos CLI utility with provided arguments
+    cmds:
+      - |
+        atmos {{.CLI_ARGS}}
+    preconditions:
+      - sh: '[[ "${TF_VAR_state_passphrase}" != "" ]]'
+        msg: "Local AGE private key required to decrypt state: {{.SOPS_AGE_KEY_FILE}}\nTry running task sops:init"
+
+  up:
+    desc: Run atmos CLI utility workflow to bring up environment
+    cmds:
+      - atmos workflow up -f localhost --stack dev
+    preconditions:
+      - sh: '[[ "${TF_VAR_state_passphrase}" != "" ]]'
+        msg: "Local AGE private key required to decrypt state: {{.SOPS_AGE_KEY_FILE}}\nTry running task sops:init"
+
+  down:
+    desc: Run atmos CLI utility workflow to tear down environment
+    cmds:
+      - atmos workflow down -f localhost --stack dev
+    preconditions:
+      - sh: '[[ "${TF_VAR_state_passphrase}" != "" ]]'
+        msg: "Local AGE private key required to decrypt state: {{.SOPS_AGE_KEY_FILE}}\nTry running task sops:init"
+
+  test:state:
+    desc: Check all terraform .tfstate files have the encrypted_data element and are not empty.
+    cmds:
+      - |
+        find ./components/terraform/ -type f -name "*.tfstate" ! -path "*/.terraform/terraform.tfstate" | while read -r file; do
+          if ! jq -e '.encrypted_data' "$file" > /dev/null; then
+            if ! jq -e '.backend.config.path' "$file" | grep -q null; then
+              echo "Missing encrypted_data in $file and backend.config.path is null"
+              exit 1
+            else
+              echo "Empty State - ${file}"
+            fi
+          else
+            echo "State Encrypted: ${file}"
+          fi  
+        done
